# Exported from Render on 2026-04-16T23:59:12Z
version: "1"
services:
- type: web
  name: CHAT-GPT-GEMINI
  runtime: node
  repo: https://github.com/tezehcalvin-blip/CHAT-GPT-GEMINI
  plan: free
  envVars:
  - key: tct_6f6c8813
    sync: true
  - key: AQ.Ab8RN6KT1LJHk_HR4LefRkB4jxXHKF59n4QsTqpW5Vie-AZvRw
    sync: true
  - key: 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
    sync: true
  region: virginia
  buildCommand: npm install
  startCommand: node npm start
  autoDeployTrigger: commit
